### ISSUE TITLE
Agent trips up over UTF-8 characters from some commands

### ISSUE THREAD

**Issue by abaddononion** [choria-plugins/shell-agent#13]
Not sure how to quantify this much more, as I don't have a super firm grasp on what's happening. The easiest way I know to see the issue is to try to "rm" (with no flags) a file that doesn't exist on a Centos 7 system. The issue does not occur on either Centos 6 or Centos 8. But on Centos 7 there is apparently some UTF-8 returned in the stderr message that causes Choria to return the error "Cannot decode output from Shim for Ruby action shell#run". 

When this happens the command seems to run successfully, you just fail to get the proper response information back.

**Comment by ripienaar** [comment]
thank you
